# This file allows packrat (used by rsconnect during deployment) to pick up dependencies.
library(rhino)
library(treesitter)
library(treesitter.r)

# App dependencies (legacy scripts + Rhino modules)
library(shiny)
library(DT)
library(leaflet)
library(glue)
library(rstac)
library(httr)
library(terra)
library(htmltools)
library(leaflet.minicharts)
library(leaflet.extras)
library(leafem)
library(tidyr)
library(RColorBrewer)
library(purrr)
library(arrow)
library(dplyr)
library(lubridate)
library(mapview)
library(mapedit)
library(Rmisc)
library(ggpubr)
library(bslib)
library(stringr)
library(ggplot2)
library(sf)
library(viridisLite)
library(suntools)
